Update Button String Configs / Add Quartet
Adjusted button strings. Updated to 'quartet.xml' instead of 'quartet2a.xml' for additional versions for pre-system16. After running the script, you will receive the following errors due to the 'quartet.xml' housing all quartet roms "Quartet/Quartet 2". If you do not wish to support the four player version of Quartet, I understand. They are the same game just updated player counts from 4 to 2.

quartet         Quartet (Rev A, 8751 315-5194)
ERROR: MAME defines a different button count (2) for game quartet (found 3)
Button config string: Jump,Shot,-

quarteta        Quartet (8751 315-5194)
ERROR: MAME defines a different button count (2) for game quarteta (found 3)
Button config string: Jump,Shot,-

Tetris will throw the following error as this Taito conversion is missing setwords. It shouldn't even be supported as it's just a conversion.

tetrista        Tetris (Japan, Taito B-System, Master of Weapon Conversion Kit)
Error: cannot find region sprites used in -setword argument